traits:
  '00bkg':
    NONE: 0
    bkg04: 15
    bkg05: 14
    bkg07: 14
    bkg06: 14
    bkg02: 14
    bkg03: 14
    bkg01: 15
  '01body':
    NONE: 0
    body01: 100
  '02cheeks':
    NONE: 21
    cheeks09: 3
    cheeks08: 8
    cheeks12: 8
    cheeks06: 8
    cheeks07: 3
    cheeks05: 8
    cheeks11: 8
    cheeks10: 8
    cheeks04: 8
    cheeks1: 3
    cheeks03: 3
    cheeks02: 3
    cheeks13: 8
  '03eye':
    NONE: 0
    Eye13: 1
    Eye07: 5
    Eye06: 5
    Eye12: 3
    Eye04: 5
    Eye10: 5
    Eye11: 3
    Eye05: 5
    Eye29: 1
    Eye01: 8
    Eye15: 3
    Eye14: 3
    Eye28: 1
    Eye16: 3
    Eye02: 5
    Eye03: 6
    Eye17: 3
    Eye26: 1
    Eye27: 1
    Eye25: 3
    Eye19: 3
    Eye18: 3
    Eye24: 3
    Eye08: 5
    Eye20: 3
    Eye21: 3
    Eye09: 1
    Eye23: 3
    Eye22: 3
    Eye30: 3
  '04beak':
    NONE: 0
    Beak08: 6
    Beak09: 7
    Beak04: 10
    Beak10: 8
    Beak11: 8
    Beak05: 8
    Beak13: 3
    Beak07: 8
    Beak06: 8
    Beak12: 7
    Beak02: 8
    Beak03: 9
    Beak01: 10
    Beak14: 0
  '05face':
    NONE: 63
    face05: 4
    face04: 4
    face06: 4
    face07: 4
    face03: 4
    face02: 0
    face01: 13
    face08: 0
    face09: 0
    face10: 4
  '06hat':
    NONE: 31
    hat01: 6
    hat02: 6
    hat03: 6
    hat04: 6
    hat05: 6
    hat06: 7
    hat07: 7
    hat08: 7
    hat09: 7
    hat10: 7
    hat11: 7
    hat12: 7
    hat13: 7
    hat14: 7
    hat15: 7
    hat16: 7
    hat17: 6
    hat18: 6
    hat19: 7
    hat20: 2
    hat21: 2
    hat22: 6
    hat23: 4
    hat24: 6
    hat25: 6
    hat26: 4
    hat27: 4
    hat28: 4
    hat29: 6
    hat30: 6
    hat31: 6
    hat32: 6
    hat33: 4
    hat34: 6
    hat35: 6
    hat36: 0
    hat37: 6
    hat38: 6
    hat39: 2
    hat40: 0
    hat41: 2
    hat42: 2
    hat43: 4
    hat44: 4
    hat45: 4
    hat46: 2
    hat47: 4
    hat48: 4
    hat49: 4
    hat50: 2
    hat51: 4
    hat52: 4
    hat53: 4
    hat54: 4
    hat55: 2
    hat56: 2
    hat57: 2
    hat58: 2
    hat59: 2
    hat60: 2
    hat61: 2
    hat62: 4
    hat63: 4
    hat64: 1
    hat65: 4
    hat66: 4
    hat67: 4
    hat68: 4
    hat69: 4
    hat70: 4
    hat71: 4
    hat72: 4
    hat73: 4
    hat74: 4
    hat75: 4
    hat76: 6
    hat77: 4
    hat78: 2
    hat79: 6
    hat80: 1
    hat81: 4
    hat82: 6
    hat83: 6
    hat84: 1
  '07clothes':
    NONE:  22
    clothes28: 6
    clothes14: 6
    clothes15: 6
    clothes01: 5
    clothes29: 4
    clothes17: 5
    clothes03: 1
    clothes02: 5
    clothes16: 6
    clothes12: 6
    clothes06: 6
    clothes07: 5
    clothes13: 5
    clothes05: 6
    clothes11: 6
    clothes39: 1
    clothes38: 6
    clothes10: 6
    clothes04: 5
    clothes09: 6
    clothes21: 6
    clothes35: 4
    clothes34: 4
    clothes20: 6
    clothes08: 6
    clothes36: 6
    clothes22: 6
    clothes23: 6
    clothes37: 5
    clothes33: 4
    clothes27: 6
    clothes26: 1
    clothes32: 4
    clothes24: 5
    clothes30: 4
    clothes18: 6
    clothes19: 6
    clothes31: 4
    clothes25: 1
    clothes40: 5
    clothes41: 4
    clothes42: 1
    clothes43: 2
    clothes44: 5
    clothes45: 5
    clothes46: 5
    clothes47: 4
    clothes48: 5
    clothes49: 5
    clothes50: 5
    clothes51: 5
    clothes52: 0
    clothes53: 5
    clothes54: 5
    clothes55: 5
    clothes56: 5
    clothes57: 5
    clothes58: 5
    clothes59: 5
    clothes60: 5
    clothes61: 5
    clothes62: 6
    clothes63: 6
    clothes64: 6
    clothes65: 6
    clothes66: 5
    clothes67: 5
    clothes68: 5
    clothes69: 5
    clothes70: 4
    clothes71: 4
    clothes72: 5
    clothes73: 4
    clothes74: 5
    clothes75: 5
    clothes76: 0
    clothes77: 4
    clothes78: 4
    clothes79: 1
    clothes80: 1
    clothes81: 1
    clothes82: 4
    clothes83: 4
